### PR TITLE
Updating PR review working agreements

### PR DESCRIPTION
**Pull request by burtonjc**
GitHub just released a new PR review process. It formalizes the process of someone approving a pull request. This is a much more wholistic method of review than just doing :+1:'s.

### CODE REVIEW

**Comment by burtonjc** [comment]
@jtslear, @songawee, @marydavis what do you guys think of this?

**Comment by marydavis** [comment]
haha, i was just commenting on that second sentence but you rewrote it, lol.

**Comment by songawee** [comment]
👍

**Comment by burtonjc** [comment]
haha, @marydavis and @songawee you are breaking the new working agreement already! you are supposed to "approve" it, not give a 👍 !

**Comment by songawee** [comment]
I tried but it just says that John approved it. I couldn't figure out how to approve.

**Comment by marydavis** [comment]
I used the new built in code review process, but since we all needed to approve i chose the first option in submitting my review without explicit approval since i wasn't the final say :)

**Comment by songawee** [comment]
oh, lame. you have to go to the `files changed` page to actually approve

**Pull request merged**
