### PR TITLE
Suggest making it a working agreement to make work public when it can be

### PR DESCRIPTION
**Pull request by homeyer**
closes waffleio/waffle.io-biz#478

### CODE REVIEW

**Comment by burtonjc** [comment]
:+1:

**Comment by marydavis** [comment]
:+1:

**Comment by homeyer** [comment]
@ashumz @kellihsf @nparsons08 waiting on you

**Comment by kellihsf** [comment]
:+1:

**Comment by nparsons08** [comment]
:+1:

**Pull request merged**
